/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * react-cache-tools backend
 * The react-cache-tools backend API description
 * OpenAPI spec version: 1.0
 */
import type { CreateUserDtoSex } from "./createUserDtoSex";

export interface CreateUserDto {
  /**
   * @minimum 1
   * @maximum 150
   */
  age: number;
  /** @maxLength 100 */
  email: string;
  /** @maxLength 100 */
  name: string;
  /** @maxLength 255 */
  note?: string;
  sex: CreateUserDtoSex;
}
